UnreachableError: don't allow empty ctor
UnreachableError should be treated like an assertion. As such, we should
require that callers provide a meaningful message.